
(function(){
'use strict';
var CFG=window.APP_CONFIG||{};
var DEMO=new URLSearchParams(location.search).get('demo')==='1';
var state={sessions:[],coaches:[],calendar:{},changes:[],terms:[],themes:{},me:null,screen:'home',week:null,financials:null,unlocked:false};
var root=document.getElementById('screen-root');
var sheet=document.getElementById('sheet'),sheetContent=document.getElementById('sheet-content');
var DAY_ORDER=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
var icons={pin:'⌖',clock:'◷',users:'●',calendar:'▣',book:'▤',shield:'◆',phone:'☎',doc:'▧',bell:'◉',gear:'⚙',money:'£',person:'●'};
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function headerKey(s){return String(s||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')}
function parseCsv(text){var rows=[],row=[],field='',q=false;for(var i=0;i<text.length;i++){var c=text[i],n=text[i+1];if(q){if(c==='"'&&n==='"'){field+='"';i++}else if(c==='"'){q=false}else field+=c}else{if(c==='"')q=true;else if(c===','){row.push(field);field=''}else if(c==='\n'){row.push(field);rows.push(row);row=[];field=''}else if(c!=='\r')field+=c}}row.push(field);if(row.some(Boolean))rows.push(row);return rows}
function objects(text){var rows=parseCsv(text),h=(rows.shift()||[]).map(headerKey);return rows.map(function(r){var o={};h.forEach(function(k,i){if(k)o[k]=(r[i]||'').trim()});return o})}
function fetchCsv(url){if(!url||/^PASTE_/.test(url))return Promise.resolve([]);return fetch(url,{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('Could not load data');return r.text()}).then(objects)}
function nameKey(s){return String(s||'').trim().toLowerCase().replace(/\s+/g,' ')}
function splitCoaches(s){return String(s||'').split(',').map(function(x){return x.trim()}).filter(Boolean)}
function parseDate(s){if(!s)return null;var m=String(s).match(/^(\d{4})-(\d{2})-(\d{2})/);return m?new Date(+m[1],+m[2]-1,+m[3],12):null}
function mondayOf(d){d=new Date(d||new Date());d.setHours(12,0,0,0);var day=d.getDay()||7;d.setDate(d.getDate()-day+1);return d}
function iso(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function money(v){var n=Number(v);return isFinite(n)?new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(n):'—'}
function demoData(){
 state.sessions=[
{id:'E01',programme:'Evening',category:'Development Centre',name:'U9/10 Development',ageGroup:'U9/10',day:'Thursday',time:'17:30 - 18:30',venue:"City of London Freemen's",address:'Ashtead, KT21',coaches:['David','Charlie'],participants:'12'},
{id:'E02',programme:'Evening',category:'Academy',name:'U12 Academy',ageGroup:'U12',day:'Thursday',time:'19:00 - 20:30',venue:"City of London Freemen's",address:'Ashtead, KT21',coaches:['David','Charlie'],participants:'14'},
{id:'E03',programme:'Evening',category:'Development Centre',name:'U13/14 Development',ageGroup:'U13/14',day:'Friday',time:'18:00 - 19:00',venue:'Therfield School',address:'Leatherhead',coaches:['David'],participants:'15'},
{id:'D01',programme:'Day',category:'School',name:"St Peter's After School",ageGroup:'',day:'Friday',time:'16:00 - 17:00',venue:"St Peter's School",address:'Leatherhead',coaches:['David'],participants:'18'},
{id:'E04',programme:'Evening',category:'Development Centre',name:'U8 Development',ageGroup:'U8',day:'Thursday',time:'16:30 - 17:30',venue:"City of London Freemen's",address:'Ashtead, KT21',coaches:['Jack'],participants:'11'}];
 state.me={name:'David',owner:true}; state.week=iso(mondayOf(new Date(2026,8,17)));
 state.themes[state.week]={'development centre':'Receiving to play forward','academy':'Playing through pressure','school':'1v1 attacking'};
 state.calendar[state.week]={label:'Term 1 Week 1',running:true};
 state.financials={E01:{participants:'12',revenue_net:'144',coach_cost:'48',venue_cost:'32',profit:'64'},E02:{participants:'14',revenue_net:'168',coach_cost:'60',venue_cost:'36',profit:'72'}};
 state.unlocked=true;
}
function load(){
 if(DEMO){demoData();render();return}
 root.innerHTML='<div class="loading">Loading your hub…</div>';
 Promise.all([fetchCsv(CFG.sessionsCsvUrl),fetchCsv(CFG.calendarCsvUrl),fetchCsv(CFG.changesCsvUrl),fetchCsv(CFG.termsCsvUrl),fetchCsv(CFG.themesCsvUrl)]).then(function(all){
  var ss=all[0];state.sessions=ss.map(function(r){return {id:r.session_id,name:r.session_name,programme:r.programme,category:r.category,ageGroup:r.age_group,day:r.day,time:r.time,venue:r.venue,address:r.address,coaches:splitCoaches(r.coaches),client:r.client,hours:r.hours}});
  var names={};state.sessions.forEach(function(s){s.coaches.forEach(function(c){names[c]=true})});var qs=new URLSearchParams(location.search);var coach=qs.get('coach');state.me={name:coach&&names[coach]?coach:(names.David?'David':Object.keys(names)[0]||'Coach'),owner:false};
  all[1].forEach(function(r){var d=parseDate(r.week_commencing);if(d)state.calendar[iso(mondayOf(d))]={label:r.label||'',weekNo:r.week_no||'',running:!/^(no|n|0|false)$/i.test(r.running||'yes')}});
  state.changes=all[2];state.terms=all[3];all[4].forEach(function(r){var d=parseDate(r.week_commencing);if(!d)return;var k=iso(mondayOf(d));state.themes[k]=state.themes[k]||{};state.themes[k][nameKey(r.category)]=r.theme||''});state.week=iso(mondayOf(new Date()));render();
 }).catch(function(e){root.innerHTML='<div class="error"><b>Could not load the Hub.</b><br>'+esc(e.message)+'</div>'})
}
function mine(){return state.sessions.filter(function(s){return !state.me||s.coaches.some(function(c){return nameKey(c)===nameKey(state.me.name)})})}
function dayIndex(day){return DAY_ORDER.indexOf(day)}
function sessionsForDisplay(){return mine().slice().sort(function(a,b){var d=dayIndex(a.day)-dayIndex(b.day);if(d)return d;return a.time.localeCompare(b.time)})}
function todayName(){return DAY_ORDER[(new Date()).getDay()-1]||'Thursday'}
function themeFor(s){var w=state.themes[state.week]||{};return w[nameKey(s.category)]||''}
function sessionRow(s,accent){return '<button class="session-row" data-session="'+esc(s.id)+'"><span class="session-accent '+(accent||'')+'"></span><span><span class="session-time">'+esc(s.time)+'</span><span class="session-title">'+esc(s.name)+'</span><span class="session-sub">'+esc(s.venue)+'</span></span><span class="chev">›</span></button>'}
function nextSession(){return sessionsForDisplay()[0]||null}
function setNav(screen){document.querySelectorAll('[data-nav]').forEach(function(b){b.classList.toggle('is-active',b.dataset.nav===screen)})}
function render(){setNav(state.screen);if(state.screen==='home')renderHome();else if(state.screen==='schedule')renderSchedule();else if(state.screen==='resources')renderResources();else if(state.screen==='venues')renderVenues();else if(state.screen==='support')renderSupport();else if(state.screen==='more')renderMore();else if(state.screen==='management')renderManagement();}
function renderHome(){var n=nextSession(),today=sessionsForDisplay().slice(0,3),focus=n?themeFor(n):'';root.innerHTML='<section class="hero"><div class="eyebrow">Coach Hub</div><h1>Good morning, '+esc(state.me?state.me.name:'Coach')+'</h1><p>'+new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'})+'</p><div class="quote">“Better people make better players.”</div></section>'+
'<div class="home-grid"><div class="stack">'+(n?'<section><div class="section-head"><h2>Your next session</h2><button class="link-btn" data-nav="schedule">View all</button></div><article class="next-card" data-session="'+esc(n.id)+'"><div class="next-top"><span class="eyebrow">NEXT SESSION</span><span class="pill lime">Upcoming</span></div><h3>'+esc(n.name)+'</h3><div class="meta"><div class="meta-row">'+icons.clock+' <b>'+esc(n.time)+'</b></div><div class="meta-row">'+icons.pin+' <span>'+esc(n.venue)+'</span></div><div class="meta-row">'+icons.users+' <span>With: '+esc(n.coaches.join(' & '))+'</span></div></div><button class="primary-btn" data-session="'+esc(n.id)+'">View session details</button></article></section>':'')+
'<section><div class="section-head"><h2>Today’s sessions</h2><button class="link-btn" data-nav="schedule">See all</button></div><div class="card list">'+today.map(function(s,i){return sessionRow(s,i===0?'lime':'')}).join('')+'</div></section></div><div class="stack">'+
'<section><div class="section-head"><h2>This week’s focus</h2></div><div class="card focus-card"><div class="focus-copy"><span class="eyebrow">'+esc(n?n.category:'Development')+'</span><h3>'+esc(focus||'Develop • Belong • Achieve')+'</h3><p>Key coaching detail for the week, linked directly to your sessions.</p></div><div class="focus-visual">◎</div></div></section>'+
'<section><div class="section-head"><h2>Quick links</h2></div><div class="quick-grid"><button class="quick-card" data-nav="schedule"><span class="qicon">▣</span>My Schedule</button><button class="quick-card" data-nav="resources"><span class="qicon">▤</span>Resources</button><button class="quick-card" data-nav="venues"><span class="qicon">⌖</span>Venues</button><button class="quick-card" data-nav="support"><span class="qicon">◆</span>Coach Support</button></div></section></div></div>'}
function renderSchedule(){var list=sessionsForDisplay(),groups={};list.forEach(function(s){(groups[s.day]=groups[s.day]||[]).push(s)});root.innerHTML='<div class="page-title"><h1>My Schedule</h1><p>Your sessions, all in one place.</p></div><div class="segmented"><button class="is-active">Today</button><button>This Week</button><button>Calendar</button></div><div class="date-strip"><div class="date-chip"><small>Mon</small><b>14</b></div><div class="date-chip"><small>Tue</small><b>15</b></div><div class="date-chip"><small>Wed</small><b>16</b></div><div class="date-chip is-active"><small>Thu</small><b>17</b></div><div class="date-chip"><small>Fri</small><b>18</b></div></div>'+DAY_ORDER.filter(function(d){return groups[d]}).map(function(d){return '<section class="day-block"><h3>'+d+' '+(d==='Thursday'?'17 September 2026':'')+'</h3><div class="card list">'+groups[d].map(function(s){return sessionRow(s,'')}).join('')+'</div></section>'}).join('')+'<button class="primary-btn" data-action="add-all-calendar">▣ Add visible sessions to calendar</button>'}
function findSession(id){return state.sessions.find(function(s){return s.id===id})}
function renderSession(id){var s=findSession(id);if(!s)return;state.screen='session';setNav('schedule');var fin=state.unlocked&&state.financials&&state.financials[s.id];root.innerHTML='<section class="detail-hero"><button class="back-btn" data-nav="schedule">‹ Back</button><h1>'+esc(s.name)+'</h1><p>'+esc(s.category||s.programme)+'</p></section><div class="card detail-card"><div class="meta"><div class="meta-row">'+icons.calendar+' <b>'+esc(s.day)+'</b></div><div class="meta-row">'+icons.clock+' <span>'+esc(s.time)+'</span></div><div class="meta-row">'+icons.pin+' <span>'+esc(s.venue)+(s.address?' · '+esc(s.address):'')+'</span></div><div class="meta-row">'+icons.users+' <span>With: '+esc(s.coaches.join(' & '))+'</span></div></div><button class="primary-btn" data-action="calendar" data-session="'+esc(s.id)+'">▣ Add to Calendar</button></div><div class="card action-list"><button class="action-row" data-action="theme"><span class="action-icon">◎</span><span><b>Session theme</b><small>'+esc(themeFor(s)||'No theme published yet')+'</small></span><span>›</span></button><button class="action-row" data-nav="venues"><span class="action-icon">⌖</span><span><b>Venue information</b><small>Maps, parking, facilities</small></span><span>›</span></button><button class="action-row" data-nav="resources"><span class="action-icon">▤</span><span><b>Session resources</b><small>Plans, drills and objectives</small></span><span>›</span></button><button class="action-row"><span class="action-icon">▧</span><span><b>Session notes</b><small>Key points and reminders</small></span><span>›</span></button></div>'+(fin?'<div class="financial-mini"><b>Session Financials <small>(Management only)</small></b><div class="fm-row"><span>Participants</span><span>'+esc(fin.participants||'—')+'</span></div><div class="fm-row"><span>Revenue</span><span>'+money(fin.revenue_net||fin.revenue_gross)+'</span></div><div class="fm-row"><span>Coach cost</span><span>'+money(fin.coach_cost)+'</span></div><div class="fm-row"><span>Venue cost</span><span>'+money(fin.venue_cost)+'</span></div><div class="fm-row profit"><span>Profit</span><span>'+money(fin.profit)+'</span></div></div>':'<button class="secondary-btn" data-nav="management" style="margin-top:12px">🔒 Session financials (Management)</button>')}
function renderVenues(){var seen={},vs=[];state.sessions.forEach(function(s){if(s.venue&&!seen[s.venue]){seen[s.venue]=1;vs.push({name:s.venue,address:s.address||''})}});root.innerHTML='<div class="page-title"><h1>Venues</h1><p>Everything you need before you arrive.</p></div><div class="search"><input placeholder="Search venues…"></div><div class="chip-row"><button class="chip is-active">All</button><button class="chip">Astro</button><button class="chip">Grass</button><button class="chip">Indoor</button></div><div class="venue-list">'+vs.map(function(v){return '<article class="card venue-card"><div class="venue-thumb"></div><div><h3>'+esc(v.name)+'</h3><p>'+esc(v.address||'Venue information')+'</p><span class="pill blue">Venue info</span></div><span class="chev">›</span></article>'}).join('')+'</div>'}
function renderResources(){var cards=[['Curriculum','Second Half – Term 1','Weeks 8–14',''],['Session Plans','Passing & Receiving','Technical practices','alt'],['Coaching Games','1v1 Attacking','Games & practices','warm'],['Player Development','Centre Midfield Guide','Role, detail and examples','alt'],['Documents','Coach Behaviour & Standards','Expectations & policies',''],['Session Plans','Finishing Practices','Drills & progressions','warm']];root.innerHTML='<div class="page-title"><h1>Resources</h1><p>Session plans, curriculum, drills and useful documents.</p></div><div class="search"><input placeholder="Search resources…"></div><div class="chip-row"><button class="chip is-active">All</button><button class="chip">Curriculum</button><button class="chip">Session Plans</button><button class="chip">Coaching Games</button><button class="chip">Player Development</button></div><div class="resource-grid">'+cards.map(function(c){return '<article class="card resource-card"><div class="resource-img '+c[3]+'">'+esc(c[1])+'</div><div class="resource-body"><span class="pill blue">'+esc(c[0])+'</span><h3>'+esc(c[1])+'</h3><p>'+esc(c[2])+'</p></div></article>'}).join('')+'</div>'}
function renderSupport(){var rows=[['●','Our Standards','Expectations for all coaches'],['◆','Safeguarding','Key information & procedures'],['♟','Behaviour & Conduct','On and off the pitch'],['▧','Session Guidelines','Planning and delivery'],['●','Communication','Parents, players and schools'],['▤','Policies','Key documents'],['☎','Useful Contacts','Who to contact'],['●','Coach Development','Support and opportunities']];root.innerHTML='<div class="page-title"><h1>Coach Support Centre</h1><p>Everything you need to be the best version of yourself as a coach.</p></div><div class="card support-list">'+rows.map(function(r){return '<button class="support-row"><span class="support-icon">'+r[0]+'</span><span><b>'+r[1]+'</b><small>'+r[2]+'</small></span><span>›</span></button>'}).join('')+'</div><div class="quote-card card" style="margin-top:14px"><strong>“Better people make better players.”</strong></div>'}
function renderMore(){var rows=[['●','My Profile','Update your details',''],['◉','Notifications','Manage alerts',''],['£','Management & Financials','Restricted access','management'],['●','Feedback','Share ideas or report an issue',''],['☎','Contact the Office','Get in touch',''],['↪','Log Out','','']];root.innerHTML='<div class="page-title"><h1>More</h1><p>Your account, support and management access.</p></div><div class="card more-list">'+rows.map(function(r){return '<button class="more-row" '+(r[3]?'data-nav="'+r[3]+'"':'')+'><span class="support-icon">'+r[0]+'</span><span><b>'+r[1]+'</b><small>'+r[2]+'</small></span><span>›</span></button>'}).join('')+'</div>'}
function renderManagement(){state.screen='management';setNav('more');if(state.unlocked){renderManagementDashboard();return}root.innerHTML='<section class="locked"><div class="page-title"><h1 style="color:white">Management Access</h1><p style="color:#cfe0f4">Financials & administration. Restricted to authorised users.</p></div><div class="management-card"><h2>🔒 Enter password</h2><p style="color:var(--muted);font-size:12px">This uses the same protected Financials connection as the existing Hub.</p><div class="pw"><input id="pw" type="password" placeholder="Password"><button data-action="unlock">Access</button></div><p id="pw-error" style="color:var(--red);font-size:12px"></p></div><div class="card support-list" style="margin-top:14px;background:rgba(255,255,255,.98);color:var(--ink)"><div class="support-row"><span class="support-icon">▣</span><span><b>Full schedule view</b><small>All coaches, all sessions</small></span><span>›</span></div><div class="support-row"><span class="support-icon">▤</span><span><b>Financial dashboard</b><small>Live and historical data</small></span><span>›</span></div><div class="support-row"><span class="support-icon">●</span><span><b>Coach management</b><small>Hours, rates and costs</small></span><span>›</span></div></div></section>'}
function renderManagementDashboard(){var fs=state.financials||{};var rows=Object.values(fs),rev=rows.reduce(function(a,r){return a+(+r.revenue_net||0)},0),profit=rows.reduce(function(a,r){return a+(+r.profit||0)},0);root.innerHTML='<section class="locked"><div class="page-title"><h1 style="color:white">Management Dashboard</h1><p style="color:#cfe0f4">Schedules, financials and administration.</p></div><div class="kpi-grid"><div class="kpi"><small>Sessions</small><b>'+state.sessions.length+'</b></div><div class="kpi"><small>Revenue</small><b>'+money(rev)+'</b></div><div class="kpi"><small>Profit</small><b>'+money(profit)+'</b></div><div class="kpi"><small>Coaches</small><b>'+new Set(state.sessions.flatMap(function(s){return s.coaches})).size+'</b></div></div><div class="card support-list" style="color:var(--ink)"><div class="support-row"><span class="support-icon">▣</span><span><b>Full schedule view</b><small>All coaches, all sessions</small></span><span>›</span></div><div class="support-row"><span class="support-icon">£</span><span><b>Financial dashboard</b><small>Baseline, actual and archive</small></span><span>›</span></div><div class="support-row"><span class="support-icon">●</span><span><b>Coach management</b><small>Hours, rates and costs</small></span><span>›</span></div><div class="support-row"><span class="support-icon">▧</span><span><b>Reports & exports</b><small>P&L, attendance and more</small></span><span>›</span></div></div></section>'}
function b64(b){var bin=atob(String(b).replace(/\s+/g,'')),o=new Uint8Array(bin.length);for(var i=0;i<bin.length;i++)o[i]=bin.charCodeAt(i);return o}
function unlock(pw){if(DEMO){state.unlocked=true;renderManagementDashboard();return}var f=CFG.financials;if(!f||!f.ciphertext){document.getElementById('pw-error').textContent='Financial connection is not configured.';return}crypto.subtle.importKey('raw',new TextEncoder().encode(pw),'PBKDF2',false,['deriveKey']).then(function(base){return crypto.subtle.deriveKey({name:'PBKDF2',salt:b64(f.salt),iterations:f.iterations||250000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['decrypt'])}).then(function(key){return crypto.subtle.decrypt({name:'AES-GCM',iv:b64(f.iv)},key,b64(f.ciphertext))}).then(function(buf){return fetchCsv(new TextDecoder().decode(buf).trim())}).then(function(rows){state.financials={};rows.forEach(function(r){if(r.session_id)state.financials[r.session_id]=r});state.unlocked=true;renderManagementDashboard()}).catch(function(){document.getElementById('pw-error').textContent='Incorrect password.'})}
function addCalendar(s){var title=s.name,loc=s.venue,start=new Date();var ics='BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nSUMMARY:'+title+'\r\nLOCATION:'+loc+'\r\nDESCRIPTION:Josh Evans Soccer School\r\nEND:VEVENT\r\nEND:VCALENDAR';var blob=new Blob([ics],{type:'text/calendar'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(s.name||'session').replace(/[^a-z0-9]+/gi,'-')+'.ics';a.click();setTimeout(function(){URL.revokeObjectURL(url)},1000);toast('Calendar file created')}
function toast(t){var e=document.getElementById('toast');e.textContent=t;e.hidden=false;setTimeout(function(){e.hidden=true},1800)}
document.addEventListener('click',function(e){var nav=e.target.closest('[data-nav]');if(nav){state.screen=nav.dataset.nav;render();return}var ss=e.target.closest('[data-session]');if(ss){renderSession(ss.dataset.session);return}var a=e.target.closest('[data-action]');if(!a)return;if(a.dataset.action==='unlock')unlock(document.getElementById('pw').value);if(a.dataset.action==='calendar'){var s=findSession(a.dataset.session);if(s)addCalendar(s)}if(a.dataset.action==='add-all-calendar')toast('Use each session to add it to your calendar');if(a.dataset.action==='theme')toast('Theme is pulled from the Themes sheet')});
load();
})();
